Homework 2
banea9/android-project pull request #2
Opened 2023-05-22 11:52 UTC by banea9

Hilt and Dagger
View models
Repository
JWT token functionality added
Loading spinner while fetching product

2023-05-24 10:57 UTC, yll090 requested changes

2023-05-24 10:57 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/LoginScreen.kt
> +    response?.let { result ->
Even if using the flow variables as state, monitoring the changes should always pass throught some sort of an `effect`, like `LaunchedEffect` or `SideEffect`, depending on the requirement. In this case you do need the `LaunchedEffect`, as you've already guessed you need it, but you need to wrap your whole change monitoring into it. More info about it in the next lecture, or [here](https://stackoverflow.com/questions/73799916/use-of-launchedeffect-vs-sideeffect-in-jetpack-compose) and [here](https://developer.android.com/jetpack/compose/side-effects#state-effect-use-cases).

2023-05-24 10:57 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ProductsScreen.kt
> +    response?.let { result ->
Again, use `LaunchedEffect`.

2023-05-24 10:58 UTC, yll090 reviewed
I suspect this is HW 1-2? Could you rename the PR for a better readability so we know what we're looking to review? Thanks!

2023-05-25 16:05 UTC, gbuyukliev-accedia approved these changes
It's absolutely great that you've thought of using Flow! Good job! I've left one remark and a couple of notes. Approving this PR so you can merge it regardless of whether you fix those remarks or not. Addressing them in the next PR is also an option so feel free to do so!

2023-05-25 16:05 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/LoginViewModel.kt
> +    val response: StateFlow<Result<LoginResponse>?> = _response
Note: You can collect flows right here. Looks tidier than collecting them in the composable.

2023-05-25 16:05 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ProductsScreen.kt
> +    LaunchedEffect(Unit) {
Note: Not invalid but it's a bit too "React-y", so to speak. Most of those `LaunchedEffect(Unit)`s that don't subscribe to anything can be done in the `init` method of the viewmodel. Such a `LaunchedEffect` might be viable only if you didn't have a viewmodel.

2023-05-25 16:05 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ProductsScreen.kt
> +    val productState = remember { mutableStateOf<ProductDetailsModel?>(null) }
Note: Try to use the `var something by remember { mutableStateOf<Type>() }` syntax more. It saves you on referring to a `value` each time. This `val something = remember...` syntax is needed only if you want to pass the state itself (instead of the value) to a function where you can callback set its value. If it's just for local use, the `by` syntax makes things just a little easier.

2023-05-25 16:05 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/networking/API.kt
> +    @GET(value="products/{id}?populate=*")
`?populate=*` is not a given. It might change so it's better for it to be utilized as a dynamic query parameter that you just "happen" to pass a `*` to.

2023-05-25 16:59 UTC, banea9 commented
@gbuyukliev-accedia I will address your comments in the next homework

2023-05-25 16:59 UTC, merged