Homework3 ( 2.1)
banea9/android-project pull request #3
Opened 2023-06-06 19:12 UTC by banea9

Colors, dimensions, pixel perfect overall design

2023-06-07 13:51 UTC, yll090 requested changes

2023-06-07 13:51 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/login/LoginScreen.kt
> +    LaunchedEffect(response) {
Try to not rely on the response here directly. Showing the notification and navigating should happen from the `LoginScreen` composable but the rest should be contained in the viewModel. You can introduce other variables to monitor via the `LaunchedEffect`, use callbacks, etc.

2023-06-07 13:51 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/productsDetails/ProductsScreen.kt
> +    LaunchedEffect(response) {
Again, don't rely on the response in the view. Additionally, you should be using the viewModel for not only networking but also data storage. In other words, the `productState` should safely be used from the viewModel instead of the view.

2023-06-10 18:26 UTC, banea9 commented on app/src/main/java/com/example/etherealartefacts/ui/login/LoginScreen.kt
> +    LaunchedEffect(response) {
I am not sure how to address this comment.. Can you give an example or be more specific?

2023-06-12 11:41 UTC, gbuyukliev-accedia approved these changes

2023-06-12 11:41 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/login/LoginScreen.kt
> +    LaunchedEffect(response) {
The UI (the composable) doesn't need to know about any requests or their responses. You have to have a state in the view model only for the purpose of telling the view to "navigate" because it's ready. The view doesn't need to know anything about the response, let alone set a JWT token from it.

Here's an example from Google for this very use case that might be helpful: https://developer.android.com/topic/architecture/ui-layer/events#handle-viewmodel-events

2023-06-12 11:41 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/productsDetails/ProductsScreen.kt
> +    val isLoading by productsViewModel.isLoading.collectAsState()
Not that this is wrong but see the Google example I sent above. Usually the StateFlow's `collectAsState` is declared in the viewmodel itself and in the composable you just access it by calling `viewModel.isLoading`. No need to declare it here a third time - it bloats the code unnecessarily.

2023-06-14 07:01 UTC, gbuyukliev-accedia approved these changes

2023-06-14 07:01 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/login/LoginScreen.kt
> +    if(errorOccurred == false ) {
Looks great but non-UI logic that subscribes to a state should always be executed via a `LaunchedEffect`:

```
LaunchedEffect(errorOccurred) {
  if (!errorOccurred) {
    ...
  } else if (!errorOccurred && ! showedErrNotification) {
    ...
  }
}
```

2023-06-14 09:43 UTC, merged