Homework3 1
banea9/android-project pull request #5
Opened 2023-06-29 05:32 UTC by banea9

New navigation library, bottom screen with filtering.

2023-06-29 20:07 UTC, yll090 requested changes

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +                        val strokeWidth = 1.dp.toPx()
Is this a...divider? There is already [one](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary?hl=en#Divider(androidx.compose.ui.Modifier,androidx.compose.ui.graphics.Color,androidx.compose.ui.unit.Dp,androidx.compose.ui.unit.Dp)) you could use by default.

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeScreen.kt
> +                    Box {
This box seems unnecessary, any reason it is here?

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeScreen.kt
> +                    ) {
Extract the size and apply the modifiers to the `Text` itself, then you can remove the `Box`, too.

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        CategoryOption(name = "Jewellery", isChecked = false)
Those should be exported and taken from the `strings`.

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        _defaultRange.value = 35f..150f
This should be extracted since you're using it multiple times, you can do it even here, in this file, but it should not be repeated.

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        if ((_options[0].isChecked && (!_options[1].isChecked && !_options[2].isChecked && !_options[3].isChecked && !_options[4].isChecked))) {
You have default values for other criteria, couldn't you just set a default index for options and check for it instead? The whole condition of adding filter counts could be refactored, it's a bit confusing/not readable to remove/add/remove counts.

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        if (filtered != 0f..200f) {
Same goes for this range -- reuse it.

2023-06-29 20:07 UTC, yll090 commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        println("range $range")
Remove debugging code.

2023-06-29 21:36 UTC, gbuyukliev-accedia approved these changes
Left some comments. The biggest issue in this PR is the filtering logic - really overcomplicated manual calculations, changing default values and no exported constants lead to them being very hard to understand.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +            Column(
This should be extracted to a composable, just like `CategoriesAccordion`.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +            Column {
This should be extracted to a composable, just like `CategoriesAccordion`.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +                        Icon(
When you extract the whole rating composable, this should further be extracted to another composable in the same file. Always extract list items as separate composables, no matter how small are they.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +                    valueRange = 0f..200f,
Those values should both be extracted as constants. You shouldn't have hardcoded values anywhere in the code.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +                        val strokeWidth = 1.dp.toPx()
If this is a divider, you don't need this code indeed. But if it isn't - `1.dp` should be extracted to a dimens.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +                Text(
This `Text` will be extremely hard to click without some padding to give it more click area.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/Filter.kt
> +                        text = "${stringResource(id = R.string.price_sign)}${displayedRange.value.start}",
`NumberFormat.getCurrencyInstance(Locale.US).format(number)` gives you the dollar sign out of the box. Also, those values should be formatted to 2 decimal points, always, as per the design.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeScreen.kt
> +                        Icon(
Once again - very hard to click without some inner padding or a container with padding where the onClick resides.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeScreen.kt
> +                Box(
You don't need even a single `Box` here, let alone two of them.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +    private val _options = mutableStateListOf(
There is an endpoint that returns all categories, you don't need to hardcode them yourself.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +    private val _defaultStarRating = MutableStateFlow(4)
Extract as a constant.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +    private val _defaultRange = MutableStateFlow(35f..150f)
Extract as constants. Also, this doesn't need to be a state as it never changes.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +    private val _filteredRange = MutableStateFlow(0f..200f)
Extract as a constants.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +    private val _areCategoriesUpdated = MutableStateFlow(false)
Those three don't need to be states as you're using them like plain variables - you never subscribe to them either from a `.collect` or from the UI.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        _defaultRange.value =
Why are you changing the default range? Isn't the idea behind a "default" value to never be changed?

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        _filterCount.value += 1
Why are you adding count and then removing count after conditionals? It would be far more readable if you just added *or* removed count, not both at the same time.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        if (criteria.isNotEmpty() || _areCategoriesUpdated.value || _isRangeChanged.value || _isRatingChanged.value) {
Why is this needed? You can have `allProducts` and `filteredProducts` where if no filters are applied you just make `filteredProducts = allProducts` and the UI works always with `filteredProducts`. No need for a third variable.

2023-06-29 21:36 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/etherealartefacts/ui/home/HomeViewModel.kt
> +        if ((_options[0].isChecked && (!_options[1].isChecked && !_options[2].isChecked && !_options[3].isChecked && !_options[4].isChecked))) {
For a lot of things you do in this file you can use functions instead. But this is probably the best example.

Not sure why you need the first to be truthy and the others to be falsy but something like `_options.all { !it.isChecked }` would far more easily tell you if every `isChecked` is `false`.

2023-06-30 08:59 UTC, merged

2023-06-30 09:10 UTC, gbuyukliev-accedia commented
Good that you merged it so you can continue forward! However, if you have some spare time later, please look into extracting the hardcoded values as constants, even though you've consolidated them into a single source of truth which is great, as well as the filtering logic, avoiding manual count addition/reduction.